# Generated by Django 6.0.1 on 2026-01-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_intro', models.TextField(blank=True, null=True, verbose_name='服务介绍')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='基础价格')),
                ('price_range', models.CharField(blank=True, max_length=50, null=True, verbose_name='价格区间')),
                ('is_negotiable', models.BooleanField(default=True, verbose_name='接受议价')),
                ('camera_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='相机型号')),
                ('can_provide_makeup', models.BooleanField(default=False, verbose_name='可提供化妆')),
                ('can_provide_costume', models.BooleanField(default=False, verbose_name='可提供服装')),
                ('completed_orders', models.IntegerField(default=0, verbose_name='完成订单数')),
                ('average_rating', models.FloatField(default=0.0, verbose_name='平均评分')),
                ('view_count', models.IntegerField(default=0, verbose_name='被查看次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '创作者档案',
                'verbose_name_plural': '创作者档案',
                'db_table': 'creator_profiles',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='作品标题')),
                ('image', models.ImageField(upload_to='works/', verbose_name='作品图片')),
                ('description', models.TextField(blank=True, null=True, verbose_name='作品描述')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('shooting_time', models.DateTimeField(blank=True, null=True, verbose_name='拍摄时间')),
                ('shooting_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='拍摄地点')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览数')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
                'db_table': 'works',
                'ordering': ['-created_at'],
            },
        ),
    ]
