# Generated by Django 6.0.1 on 2026-02-07 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务名称')),
                ('description', models.TextField(verbose_name='服务描述')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='基础价格')),
                ('price_range', models.CharField(blank=True, max_length=50, null=True, verbose_name='价格区间')),
                ('estimated_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='预计时长')),
                ('is_negotiable', models.BooleanField(default=True, verbose_name='接受议价')),
                ('is_available', models.BooleanField(default=True, verbose_name='可接单')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('order_count', models.IntegerField(default=0, verbose_name='接单次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='创作者')),
            ],
            options={
                'verbose_name': '服务项目',
                'verbose_name_plural': '服务项目',
                'db_table': 'services',
                'ordering': ['-created_at'],
            },
        ),
    ]
