# Generated by Django 5.2.11 on 2026-02-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0004_alter_creatorprofile_id_alter_service_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='地点名称')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='纬度')),
                ('description', models.TextField(blank=True, null=True, verbose_name='简短描述')),
                ('category', models.CharField(blank=True, choices=[('landmark', '地标打卡型'), ('nature', '自然景观型'), ('life', '校园生活型'), ('architecture', '典型建筑型')], max_length=20, null=True, verbose_name='分类')),
                ('campus', models.CharField(blank=True, choices=[('wl', '文理学部'), ('gc', '工学部'), ('xx', '信息学部'), ('yx', '医学部'), ('other', '其他')], max_length=20, null=True, verbose_name='学部')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '拍摄地点',
                'verbose_name_plural': '拍摄地点',
                'db_table': 'locations',
                'ordering': ['name'],
            },
        ),
    ]
