# Generated by Django 5.2.11 on 2026-02-22 06:27

from django.db import migrations

def import_locations(apps, schema_editor):
    Location = apps.get_model('creators', 'Location')
    
    # 整理自预设地点库的所有地点（已去重，并补充描述和学部）
    locations_data = [
        # 一、地标打卡型
        ('国立武汉大学牌坊', 114.349924, 30.528474, '起点，归处。', 'landmark', 'wl'),
        ('老图书馆', 114.361300, 30.542500, '青瓦飞檐，时光慢镜头。', 'landmark', 'wl'),
        ('樱花大道', 114.361800, 30.541900, '樱吹雪时，青春入镜。', 'landmark', 'wl'),
        ('樱顶（老图书馆上方平台）', 114.361300, 30.542800, '俯瞰樱花潮，坐看四季书。', 'landmark', 'wl'),
        ('老斋舍（樱花城堡）', 114.361200, 30.542400, '百步梯，一阶一春秋。', 'landmark', 'wl'),
        ('行政楼', 114.360900, 30.543800, '珞珈脊梁，见证启程。', 'landmark', 'wl'),
        ('万林艺术博物馆', 114.357093, 30.539265, '2015年开馆，校友陈东升捐建。', 'landmark', 'wl'),
        ('万林楼顶露台', 114.357100, 30.539300, '可俯瞰教五草坪及周边老建筑群。', 'landmark', 'wl'),
        
        # 二、自然景观型
        ('凌波门栈桥', 114.369200, 30.541200, '东临珞珈，以观沧海。', 'nature', 'wl'),
        ('东湖绿道（武大段）', 114.371500, 30.540800, '左书声，右湖光。', 'nature', 'wl'),
        ('珞珈山环山路', 114.358500, 30.539200, '山高水长，流风甚美', 'nature', 'wl'),
        ('珞珈山十八栋', 114.356800, 30.538500, '珞珈东南半岭雄，英伦别墅十八栋。', 'nature', 'wl'),
        ('樱花大道（春季限定）', 114.361800, 30.541900, '樱吹雪时，青春入镜。', 'nature', 'wl'),
        ('银杏季（教五/枫园）', 114.364100, 30.539100, '', 'nature', 'wl'),
        # 九一二操场在自然景观型和校园生活型中重复，只保留校园生活型，此处不导入
        
        # 三、校园生活型
        ('教五楼（含教五门前大草坪）', 114.364100, 30.539100, '"武大人的乌托邦"。', 'life', 'wl'),
        ('九一二操场', 114.360734, 30.541093, '惟楚有材，于斯为盛。', 'life', 'wl'),
        ('奥场', 114.367800, 30.540200, '红色跑道，通向未来。', 'life', 'wl'),
        ('梅园小操场', 114.359800, 30.540900, '露天光影，续数十年青春。', 'life', 'wl'),
        ('湖滨操场', 114.367000, 30.543000, '临湖起跑，风过耳畔。', 'life', 'wl'),
        ('枫园', 114.365800, 30.544500, '枫红如约，年复一年。', 'life', 'wl'),
        ('工学部主教（粉色楼梯）', 114.362800, 30.537500, '原武汉水利电力学院主楼，校内标志性教学楼。', 'life', 'gc'),
        ('工学部十舍（网红宿舍）', 114.364200, 30.537200, '九十年代建成，工学部学生宿舍。', 'life', 'gc'),
        ('信息学部主教（青楼）', 114.366200, 30.532500, '青灰楼宇，聚测绘智慧。', 'life', 'xx'),
        
        # 四、典型建筑型
        ('宋卿体育馆', 114.363800, 30.541000, '一九三六，百年回响。', 'architecture', 'wl'),
        ('鲲鹏广场', 114.362168, 30.538599, '"鲲鹏展翅，扶摇而上者九万里。"', 'architecture', 'wl'),
        ('自强大道', 114.362800, 30.536800, '自强、弘毅、求是、创新', 'architecture', 'wl'),
        ('医学部白宫', 114.345200, 30.556800, '白衣初心，筑梦医学。', 'architecture', 'yx'),
        ('星湖', 114.366500, 30.532800, '"甚美池"。', 'architecture', 'xx'),
        ('万林艺术博物馆外墙', 114.357093, 30.539265, '', 'architecture', 'wl'),
        ('半山庐', 114.357200, 30.539800, '1930年代建，珞珈山半山别墅。', 'architecture', 'wl'),
        ('周恩来故居', 114.356500, 30.538900, '推门，仿佛听见那年春天。', 'architecture', 'wl'),
        ('老外文楼', 114.357460, 30.542240, '青藤老墙，窗外曾有拜伦和雪莱。', 'architecture', 'wl'),
    ]
    
    for name, lng, lat, desc, cat, campus in locations_data:
        # 避免重复导入（根据名称唯一）
        if not Location.objects.filter(name=name).exists():
            Location.objects.create(
                name=name,
                longitude=lng,
                latitude=lat,
                description=desc,
                category=cat,
                campus=campus,
                is_active=True
            )

def reverse_func(apps, schema_editor):
    Location = apps.get_model('creators', 'Location')
    Location.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('creators', '0005_add_location_model'),  
    ]
    operations = [
        migrations.RunPython(import_locations, reverse_func),
    ]
