# Generated by Django 5.2.11 on 2026-02-22 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0006_import_preset_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='creators.location', verbose_name='关联地点'),
        ),
    ]
