# Generated by Django 5.2.11 on 2026-02-22 08:15

import django.db.models.deletion
from django.db import migrations, models


def migrate_work_images(apps, schema_editor):
    """将原有 Work 的单张图片迁移到新 WorkImage 表中"""
    Work = apps.get_model('creators', 'Work')
    WorkImage = apps.get_model('creators', 'WorkImage')
    for work in Work.objects.all():
        if work.image:
            WorkImage.objects.create(
                work=work,
                image=work.image,
                order=0
            )


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0008_add_like_comment_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='work',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, help_text='自动从上传图片的第一张生成', null=True, upload_to='works/', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='worklike',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='works/', verbose_name='图片文件')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='creators.work', verbose_name='所属作品集')),
            ],
            options={
                'verbose_name': '作品图片',
                'verbose_name_plural': '作品图片',
                'db_table': 'work_images',
                'ordering': ['order'],
                'unique_together': {('work', 'order')},
            },
        ),
        migrations.RunPython(migrate_work_images, reverse_code=migrations.RunPython.noop),
    ]
