# Generated by Django 5.2.11 on 2026-02-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0009_work_display_order_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='创作者标签'),
        ),
    ]
