# Generated by Django 6.0.1 on 2026-02-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='user',
            name='completed_orders',
            field=models.IntegerField(default=0, verbose_name='完成订单数'),
        ),
        migrations.AddField(
            model_name='user',
            name='creator_application_status',
            field=models.CharField(choices=[('not_applied', '未申请'), ('pending', '审核中'), ('approved', '已通过'), ('rejected', '已拒绝')], default='not_applied', max_length=20, verbose_name='创作者申请状态'),
        ),
        migrations.AddField(
            model_name='user',
            name='creator_applied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创作者申请时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_creator',
            field=models.BooleanField(default=True, verbose_name='是否活跃创作者'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='是否已认证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='学号'),
        ),
    ]
