# Generated by Django 5.2.11 on 2026-04-08 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_bio_user_completed_orders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorSampleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='creator_samples/', verbose_name='样片图片')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_images', to=settings.AUTH_USER_MODEL, verbose_name='申请用户')),
            ],
            options={
                'verbose_name': '创作者样片',
                'verbose_name_plural': '创作者样片',
                'db_table': 'creator_sample_images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
