# Generated by Django 5.2.11 on 2026-02-22 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('rent', '出租'), ('lease', '求租')], max_length=20, verbose_name='信息类型')),
                ('category', models.CharField(choices=[('camera', '摄影器材'), ('lens', '镜头'), ('drone', '无人机'), ('other', '其他')], max_length=20, verbose_name='设备类别')),
                ('device_model', models.CharField(max_length=100, verbose_name='设备型号')),
                ('rent_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='日租金')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='押金')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('active', '进行中'), ('closed', '已关闭')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_posts', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '设备信息',
                'verbose_name_plural': '设备信息',
                'db_table': 'equipment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post_type', 'status', 'created_at'], name='equipment_post_ty_971d64_idx'), models.Index(fields=['category', 'created_at'], name='equipment_categor_09e1d1_idx')],
            },
        ),
    ]
