# Generated by Django 6.0.1 on 2026-04-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='押金'),
        ),
        migrations.CreateModel(
            name='EquipmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='equipment/', verbose_name='设备图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='equipment.equipment', verbose_name='设备信息')),
            ],
            options={
                'verbose_name': '设备图片',
                'verbose_name_plural': '设备图片',
                'db_table': 'equipment_images',
                'ordering': ['created_at'],
            },
        ),
    ]
