# Generated by Django 5.2.11 on 2026-02-22 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_chat_messag_recieve_94b774_idx_and_more'),
        ('groupbuy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_receive_7a2967_idx',
            old_name='chat_messag_receive_14362e_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='groupbuy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='groupbuy.groupbuy', verbose_name='关联拼单（群聊用）'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('private', '私聊'), ('groupbuy', '拼单群聊')], default='private', max_length=20, verbose_name='消息类型'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='接收者（私聊用）'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type', 'groupbuy'], name='chat_messag_message_ea6361_idx'),
        ),
        migrations.AlterModelTable(
            name='message',
            table='chat_messages',
        ),
    ]
