# Generated by Django 6.0.1 on 2026-02-07 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='需求标题')),
                ('demand_type', models.CharField(choices=[('photo', '约拍'), ('makeup', '妆造'), ('retouch', '修图')], max_length=20, verbose_name='需求类型')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('shooting_time', models.DateTimeField(verbose_name='拍摄时间')),
                ('location', models.CharField(max_length=200, verbose_name='拍摄地点')),
                ('campus_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='校内地点')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='预算')),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='最低预算')),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='最高预算')),
                ('people_count', models.IntegerField(default=1, verbose_name='人数')),
                ('status', models.CharField(choices=[('pending', '待接单'), ('matched', '已接单'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('special_topic', models.CharField(blank=True, max_length=50, null=True, verbose_name='特色专题')),
                ('reference_images', models.JSONField(blank=True, default=list, verbose_name='参考图')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('matched_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_demands', to=settings.AUTH_USER_MODEL, verbose_name='匹配的创作者')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_demands', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '需求',
                'verbose_name_plural': '需求',
                'db_table': 'demands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='报价')),
                ('message', models.TextField(verbose_name='留言')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('accepted', '已接受'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_comments', to=settings.AUTH_USER_MODEL, verbose_name='创作者')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='demands.demand', verbose_name='关联需求')),
            ],
            options={
                'verbose_name': '需求评论',
                'verbose_name_plural': '需求评论',
                'db_table': 'demand_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='demand',
            index=models.Index(fields=['status', 'created_at'], name='demands_status_9ab5f0_idx'),
        ),
        migrations.AddIndex(
            model_name='demand',
            index=models.Index(fields=['demand_type', 'created_at'], name='demands_demand__16f817_idx'),
        ),
        migrations.AddIndex(
            model_name='demand',
            index=models.Index(fields=['location'], name='demands_locatio_3cb017_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='demandcomment',
            unique_together={('demand', 'creator')},
        ),
    ]
