# Generated by Django 5.2.11 on 2026-02-22 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='拼单标题')),
                ('description', models.TextField(verbose_name='拼单描述')),
                ('target_people_count', models.IntegerField(default=2, verbose_name='目标人数')),
                ('cost_per_person', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='每人费用(元)')),
                ('status', models.CharField(choices=[('recruiting', '招人中'), ('full', '已满员'), ('completed', '已完成'), ('cancelled', '已取消')], default='recruiting', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_groupbuys', to=settings.AUTH_USER_MODEL, verbose_name='发起者')),
            ],
            options={
                'verbose_name': '拼单',
                'verbose_name_plural': '拼单',
                'db_table': 'groupbuy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupBuyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('groupbuy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groupbuy.groupbuy', verbose_name='所属拼单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_groupbuys', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '拼单成员',
                'verbose_name_plural': '拼单成员',
                'db_table': 'groupbuy_member',
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='groupbuy',
            index=models.Index(fields=['status', 'created_at'], name='groupbuy_status_2bbbf9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupbuymember',
            unique_together={('groupbuy', 'user')},
        ),
    ]
